service: eventbridge-lambda-sls
frameworkVersion: '^3' # require serverless v3 or later

plugins:
  - serverless-plugin-typescript # enable TypeScript support for Lambda functions

provider:
  name: aws

  # common configuration for all Lambda functions in this stack
  runtime: nodejs14.x
  architecture: arm64 # use Graviton for running all Lambda functions

  # use --region option value or the default - us-east-1
  region: ${opt:region, "us-east-1"}

  # override the default stage (dev)
  stage: ${opt:stage, "prod"}

  # optional, Lambda function's memory size in MB, default is 1024
  memorySize: 256

  apiGateway:
    description: API Gateway for this stack

# Lambda function triggered with events from the demo-serverless-events topic
functions:
  logEvent:
    handler: src/handler.logEvent
    events:
      - eventBridge:
          eventBus: demo-serverless-events
          pattern:
            source:
              - custom.myApp
            detail-type:
              - transaction
            detail:
              location:
                - "prefix": "EUR-"

resources:
  # Override the default description
  Description: EventBridge rule invoking a Lambda function (Serverless Framework).

    